remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lab 7
description: In this lab we created our own GitHub organization and repository. We then cloned the repo to our system and created a javascript file. We then added code, committed and pushed the changes to GitHub
